// Auto-generated theme exports
// This file is automatically generated by scripts/convert-themes.js
// Do not edit manually - run 'bun run convert-themes' to regenerate

import type { CompleteTheme } from '../types/theme';

import { caffeineTheme } from './caffeine';
import { claudeTheme } from './claude';
import { cleanSlateTheme } from './clean-slate';
import { cosmicNightTheme } from './cosmic-night';
import { cyberpunkTheme } from './cyberpunk';
import { darkmatterTheme } from './darkmatter';
import { doom64Theme } from './doom64';
import { elegantLuxuryTheme } from './elegant-luxury';
import { marshmallowTheme } from './marshmallow';
import { marvelTheme } from './marvel';
import { materialDesignTheme } from './material-design';
import { midnightBloomTheme } from './midnight-bloom';
import { modernMinimalTheme } from './modern-minimal';
import { monoTheme } from './mono';
import { northernLightsTheme } from './northern-lights';
import { pastelDreamsTheme } from './pastel-dreams';
import { quantumRoseTheme } from './quantum-rose';
import { softPopTheme } from './soft-pop';
import { solarDuskTheme } from './solar-dusk';
import { spotifyTheme } from './spotify';
import { starryNightTheme } from './starry-night';
import { sunsetHorizonTheme } from './sunset-horizon';
import { vsCodeTheme } from './vs-code';

export const themes: CompleteTheme[] = [
  caffeineTheme,
  claudeTheme,
  cleanSlateTheme,
  cosmicNightTheme,
  cyberpunkTheme,
  darkmatterTheme,
  doom64Theme,
  elegantLuxuryTheme,
  marshmallowTheme,
  marvelTheme,
  materialDesignTheme,
  midnightBloomTheme,
  modernMinimalTheme,
  monoTheme,
  northernLightsTheme,
  pastelDreamsTheme,
  quantumRoseTheme,
  softPopTheme,
  solarDuskTheme,
  spotifyTheme,
  starryNightTheme,
  sunsetHorizonTheme,
  vsCodeTheme
] as const;

export const themeMap = new Map<string, CompleteTheme>([
  ['caffeine', caffeineTheme],
  ['claude', claudeTheme],
  ['clean-slate', cleanSlateTheme],
  ['cosmic-night', cosmicNightTheme],
  ['cyberpunk', cyberpunkTheme],
  ['darkmatter', darkmatterTheme],
  ['doom64', doom64Theme],
  ['elegant-luxury', elegantLuxuryTheme],
  ['marshmallow', marshmallowTheme],
  ['marvel', marvelTheme],
  ['material-design', materialDesignTheme],
  ['midnight-bloom', midnightBloomTheme],
  ['modern-minimal', modernMinimalTheme],
  ['mono', monoTheme],
  ['northern-lights', northernLightsTheme],
  ['pastel-dreams', pastelDreamsTheme],
  ['quantum-rose', quantumRoseTheme],
  ['soft-pop', softPopTheme],
  ['solar-dusk', solarDuskTheme],
  ['spotify', spotifyTheme],
  ['starry-night', starryNightTheme],
  ['sunset-horizon', sunsetHorizonTheme],
  ['vs-code', vsCodeTheme]
]);

// Individual theme exports
export { caffeineTheme };
export { claudeTheme };
export { cleanSlateTheme };
export { cosmicNightTheme };
export { cyberpunkTheme };
export { darkmatterTheme };
export { doom64Theme };
export { elegantLuxuryTheme };
export { marshmallowTheme };
export { marvelTheme };
export { materialDesignTheme };
export { midnightBloomTheme };
export { modernMinimalTheme };
export { monoTheme };
export { northernLightsTheme };
export { pastelDreamsTheme };
export { quantumRoseTheme };
export { softPopTheme };
export { solarDuskTheme };
export { spotifyTheme };
export { starryNightTheme };
export { sunsetHorizonTheme };
export { vsCodeTheme };

// Helper functions
export function getThemeById(id: string): CompleteTheme | undefined {
  return themeMap.get(id);
}

export function getAllThemeIds(): string[] {
  return Array.from(themeMap.keys());
}

export function getAllThemes(): CompleteTheme[] {
  return themes;
}
